# Generated by Django 6.0 on 2025-12-09 08:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="カルテ番号"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="氏名")),
                ("birth_date", models.DateField(verbose_name="生年月日")),
                (
                    "diagnosis",
                    models.CharField(
                        default="うつ病", max_length=200, verbose_name="診断名"
                    ),
                ),
                (
                    "medical_history",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="既往歴・禁忌チェック"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TreatmentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="実施日時"
                    ),
                ),
                (
                    "safety_sleep",
                    models.BooleanField(default=True, verbose_name="睡眠不足なし"),
                ),
                (
                    "safety_alcohol",
                    models.BooleanField(
                        default=True, verbose_name="アルコール・カフェイン過剰なし"
                    ),
                ),
                (
                    "safety_meds",
                    models.BooleanField(default=True, verbose_name="服薬変更なし"),
                ),
                (
                    "motor_threshold",
                    models.IntegerField(
                        help_text="安静時運動閾値", verbose_name="MT(%)"
                    ),
                ),
                (
                    "intensity",
                    models.IntegerField(
                        default=120, help_text="通常120%", verbose_name="刺激強度(%)"
                    ),
                ),
                (
                    "frequency",
                    models.IntegerField(default=18, verbose_name="周波数(Hz)"),
                ),
                (
                    "duration_sec",
                    models.IntegerField(default=2, verbose_name="刺激時間(秒)"),
                ),
                (
                    "interval_sec",
                    models.IntegerField(default=20, verbose_name="刺激間隔(秒)"),
                ),
                (
                    "total_pulses",
                    models.IntegerField(default=1980, verbose_name="総パルス数"),
                ),
                (
                    "adverse_events",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="有害事象・観察"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rtms_app.patient",
                        verbose_name="患者",
                    ),
                ),
            ],
        ),
    ]
