# Generated by Django 6.0 on 2025-12-09 11:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="検査実施日"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("HAM-D", "HAM-D (うつ病評価尺度)"),
                            ("BDI-II", "BDI-II (ベック抑うつ尺度)"),
                            ("QIDS", "QIDS (簡易抑うつ症状尺度)"),
                        ],
                        default="HAM-D",
                        max_length=20,
                        verbose_name="検査種別",
                    ),
                ),
                ("total_score", models.IntegerField(verbose_name="合計点")),
                (
                    "timing",
                    models.CharField(
                        choices=[
                            ("baseline", "治療前 (ベースライン)"),
                            ("week3", "3週目 (継続判定)"),
                            ("week6", "6週目 (最終評価)"),
                            ("other", "その他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="評価タイミング",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="自動判定結果などがここに入ります",
                        verbose_name="判定・特記事項",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rtms_app.patient",
                        verbose_name="患者",
                    ),
                ),
            ],
        ),
    ]
