# Generated by Django 6.0 on 2025-12-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms_app", "0002_assessment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="medical_history",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="既往歴・禁忌チェック"
            ),
        ),
        migrations.AlterField(
            model_name="treatmentsession",
            name="adverse_events",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="有害事象・観察"
            ),
        ),
    ]
