# Generated by Django 6.0 on 2025-12-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms_app", "0003_alter_patient_medical_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="admission_date",
            field=models.DateField(blank=True, null=True, verbose_name="入院予定日"),
        ),
        migrations.AddField(
            model_name="patient",
            name="first_treatment_date",
            field=models.DateField(blank=True, null=True, verbose_name="初回治療日"),
        ),
        migrations.AddField(
            model_name="patient",
            name="mapping_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="位置決め予定日"
            ),
        ),
    ]
