# Generated by Django 6.0 on 2025-12-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rtms_app",
            "0004_patient_admission_date_patient_first_treatment_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assessment",
            options={
                "verbose_name": "状態評価・心理検査",
                "verbose_name_plural": "状態評価・心理検査一覧",
            },
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={"verbose_name": "患者情報", "verbose_name_plural": "患者情報一覧"},
        ),
        migrations.AlterModelOptions(
            name="treatmentsession",
            options={
                "verbose_name": "治療実施記録",
                "verbose_name_plural": "治療実施記録一覧",
            },
        ),
        migrations.AddField(
            model_name="patient",
            name="mapping_notes",
            field=models.TextField(
                blank=True,
                help_text="MT値や刺激部位のメモなど",
                verbose_name="位置決め記録",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="questionnaire_data",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="適正質問票回答"
            ),
        ),
        migrations.AddField(
            model_name="treatmentsession",
            name="side_effect_data",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="副作用チェック"
            ),
        ),
    ]
