# Generated by Django 6.0 on 2025-12-09 15:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms_app", "0005_alter_assessment_options_alter_patient_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assessment",
            options={},
        ),
        migrations.AlterModelOptions(
            name="treatmentsession",
            options={},
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="total_score",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="mapping_notes",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="medical_history",
        ),
        migrations.RemoveField(
            model_name="treatmentsession",
            name="adverse_events",
        ),
        migrations.RemoveField(
            model_name="treatmentsession",
            name="duration_sec",
        ),
        migrations.RemoveField(
            model_name="treatmentsession",
            name="frequency",
        ),
        migrations.RemoveField(
            model_name="treatmentsession",
            name="interval_sec",
        ),
        migrations.RemoveField(
            model_name="treatmentsession",
            name="side_effect_data",
        ),
        migrations.AddField(
            model_name="assessment",
            name="scores",
            field=models.JSONField(default=dict, verbose_name="各項目スコア"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="total_score_17",
            field=models.IntegerField(default=0, verbose_name="合計点(17)"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="total_score_21",
            field=models.IntegerField(default=0, verbose_name="合計点(21)"),
        ),
        migrations.AddField(
            model_name="patient",
            name="attending_physician",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="担当医",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("M", "男性"), ("F", "女性"), ("O", "その他")],
                default="M",
                max_length=1,
                verbose_name="性別",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="life_history",
            field=models.TextField(blank=True, verbose_name="生活歴"),
        ),
        migrations.AddField(
            model_name="patient",
            name="medication_history",
            field=models.TextField(blank=True, verbose_name="薬剤治療歴"),
        ),
        migrations.AddField(
            model_name="patient",
            name="past_history",
            field=models.TextField(blank=True, verbose_name="既往歴"),
        ),
        migrations.AddField(
            model_name="patient",
            name="present_illness",
            field=models.TextField(blank=True, verbose_name="現病歴"),
        ),
        migrations.AddField(
            model_name="patient",
            name="referral_source",
            field=models.CharField(blank=True, max_length=200, verbose_name="紹介元"),
        ),
        migrations.AddField(
            model_name="treatmentsession",
            name="performer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="実施者",
            ),
        ),
        migrations.AddField(
            model_name="treatmentsession",
            name="side_effects",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="副作用チェック詳細"
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="検査日"
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="note",
            field=models.TextField(blank=True, verbose_name="判定・コメント"),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="timing",
            field=models.CharField(
                choices=[
                    ("baseline", "治療前"),
                    ("week3", "3週目"),
                    ("week6", "6週目"),
                    ("other", "その他"),
                ],
                default="other",
                max_length=20,
                verbose_name="評価時期",
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="type",
            field=models.CharField(
                choices=[("HAM-D", "HAM-D")],
                default="HAM-D",
                max_length=20,
                verbose_name="検査種別",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="mapping_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="初回位置決め日"
            ),
        ),
        migrations.AlterField(
            model_name="treatmentsession",
            name="intensity",
            field=models.IntegerField(default=120, verbose_name="刺激強度(%)"),
        ),
        migrations.AlterField(
            model_name="treatmentsession",
            name="motor_threshold",
            field=models.IntegerField(help_text="当日の設定MT", verbose_name="MT(%)"),
        ),
        migrations.CreateModel(
            name="MappingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="実施日"
                    ),
                ),
                (
                    "week_number",
                    models.IntegerField(
                        choices=[
                            (1, "第1週"),
                            (2, "第2週"),
                            (3, "第3週"),
                            (4, "その他"),
                        ],
                        default=1,
                        verbose_name="時期",
                    ),
                ),
                ("resting_mt", models.IntegerField(verbose_name="安静時MT(%)")),
                (
                    "stimulation_site",
                    models.CharField(
                        default="左DLPFC (Brainsway H1)",
                        max_length=100,
                        verbose_name="刺激部位",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="特記事項")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rtms_app.patient",
                        verbose_name="患者",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
