# Generated by Django 6.0 on 2025-12-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms_app", "0006_alter_assessment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mappingsession",
            options={},
        ),
        migrations.AddField(
            model_name="patient",
            name="mapping_notes",
            field=models.TextField(blank=True, verbose_name="位置決め記録メモ"),
        ),
    ]
