# Generated by Django 6.0 on 2025-12-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms_app", "0007_alter_mappingsession_options_patient_mapping_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="admission_type",
            field=models.CharField(
                choices=[
                    ("voluntary", "任意入院"),
                    ("medical_protection", "医療保護入院"),
                    ("emergency", "緊急措置入院"),
                    ("measure", "措置入院"),
                ],
                default="voluntary",
                max_length=20,
                verbose_name="入院形態",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_admission_procedure_done",
            field=models.BooleanField(default=False, verbose_name="入院手続き完了"),
        ),
    ]
