# Generated by Django 6.0 on 2025-12-10 01:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms_app", "0008_patient_admission_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={},
        ),
        migrations.AddField(
            model_name="patient",
            name="chief_complaint",
            field=models.CharField(blank=True, max_length=200, verbose_name="主訴"),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="日"
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="note",
            field=models.TextField(blank=True, verbose_name="特記"),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rtms_app.patient"
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="scores",
            field=models.JSONField(default=dict, verbose_name="スコア"),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="timing",
            field=models.CharField(default="other", max_length=20, verbose_name="時期"),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="total_score_17",
            field=models.IntegerField(default=0, verbose_name="合計17"),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="total_score_21",
            field=models.IntegerField(default=0, verbose_name="合計21"),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="type",
            field=models.CharField(default="HAM-D", max_length=20, verbose_name="種別"),
        ),
        migrations.AlterField(
            model_name="mappingsession",
            name="notes",
            field=models.TextField(blank=True, verbose_name="特記"),
        ),
        migrations.AlterField(
            model_name="mappingsession",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rtms_app.patient"
            ),
        ),
        migrations.AlterField(
            model_name="mappingsession",
            name="resting_mt",
            field=models.IntegerField(verbose_name="MT"),
        ),
        migrations.AlterField(
            model_name="mappingsession",
            name="stimulation_site",
            field=models.CharField(
                default="左DLPFC", max_length=100, verbose_name="部位"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="attending_physician",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="担当医",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="questionnaire_data",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="適正質問票"
            ),
        ),
        migrations.AlterField(
            model_name="treatmentsession",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="日時"
            ),
        ),
        migrations.AlterField(
            model_name="treatmentsession",
            name="intensity",
            field=models.IntegerField(default=120, verbose_name="強度"),
        ),
        migrations.AlterField(
            model_name="treatmentsession",
            name="motor_threshold",
            field=models.IntegerField(verbose_name="MT"),
        ),
        migrations.AlterField(
            model_name="treatmentsession",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rtms_app.patient"
            ),
        ),
        migrations.AlterField(
            model_name="treatmentsession",
            name="performer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="treatmentsession",
            name="safety_alcohol",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="treatmentsession",
            name="safety_meds",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="treatmentsession",
            name="safety_sleep",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="treatmentsession",
            name="side_effects",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="副作用"
            ),
        ),
        migrations.AlterField(
            model_name="treatmentsession",
            name="total_pulses",
            field=models.IntegerField(default=1980, verbose_name="パルス"),
        ),
    ]
