# Generated by Django 6.0 on 2025-12-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms_app", "0009_alter_patient_options_patient_chief_complaint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="referral_doctor",
            field=models.CharField(blank=True, max_length=100, verbose_name="紹介医"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="referral_source",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="紹介元医療機関"
            ),
        ),
    ]
