# Generated by Django 6.0 on 2025-12-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms_app", "0010_patient_referral_doctor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="discharge_prescription",
            field=models.TextField(blank=True, verbose_name="退院時処方"),
        ),
        migrations.AddField(
            model_name="patient",
            name="summary_text",
            field=models.TextField(blank=True, verbose_name="サマリー本文"),
        ),
    ]
