# Generated by Django 6.0 on 2025-12-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms_app", "0011_patient_discharge_prescription_patient_summary_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="discharge_date",
            field=models.DateField(blank=True, null=True, verbose_name="退院日"),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="timing",
            field=models.CharField(
                choices=[
                    ("baseline", "治療前 (Base)"),
                    ("week3", "3週目"),
                    ("week6", "6週目"),
                    ("other", "その他"),
                ],
                default="other",
                max_length=20,
                verbose_name="時期",
            ),
        ),
        migrations.AlterField(
            model_name="mappingsession",
            name="week_number",
            field=models.IntegerField(
                choices=[
                    (1, "第1週"),
                    (2, "第2週"),
                    (3, "第3週"),
                    (4, "第4週"),
                    (5, "第5週"),
                    (6, "第6週"),
                    (99, "その他"),
                ],
                default=1,
                verbose_name="時期",
            ),
        ),
    ]
