# Generated by Django 6.0 on 2025-12-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms_app", "0012_patient_discharge_date_alter_assessment_timing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="course_number",
            field=models.IntegerField(default=1, verbose_name="クール数"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="card_id",
            field=models.CharField(max_length=20, verbose_name="カルテ番号"),
        ),
    ]
