# Generated by Django 5.0.14 on 2025-12-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms_app", "0013_patient_course_number_alter_patient_card_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "入院待ち"),
                    ("inpatient", "入院中"),
                    ("discharged", "退院済"),
                ],
                db_index=True,
                default="waiting",
                max_length=16,
            ),
        ),
    ]
