# Generated by Django 5.0.14 on 2025-12-15 04:34

import rtms_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms_app", "0014_patient_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=rtms_app.models.consent_upload_to)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
