# Generated by Django 5.0.14 on 2025-12-15 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms_app", "0015_consentdocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assessment",
            options={"verbose_name": "評価", "verbose_name_plural": "評価"},
        ),
        migrations.AlterModelOptions(
            name="consentdocument",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "説明同意書",
                "verbose_name_plural": "説明同意書",
            },
        ),
        migrations.AlterModelOptions(
            name="mappingsession",
            options={
                "verbose_name": "位置決めセッション",
                "verbose_name_plural": "位置決めセッション",
            },
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={"verbose_name": "患者", "verbose_name_plural": "患者"},
        ),
        migrations.AlterModelOptions(
            name="treatmentsession",
            options={
                "verbose_name": "治療セッション",
                "verbose_name_plural": "治療セッション",
            },
        ),
        migrations.AlterField(
            model_name="assessment",
            name="timing",
            field=models.CharField(
                choices=[
                    ("baseline", "治療前評価"),
                    ("week3", "3週目評価"),
                    ("week6", "6週目評価"),
                    ("other", "その他"),
                ],
                default="other",
                max_length=20,
                verbose_name="時期",
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "target_model",
                    models.CharField(max_length=100, verbose_name="対象モデル"),
                ),
                ("target_pk", models.CharField(max_length=50, verbose_name="対象PK")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "作成"),
                            ("UPDATE", "更新"),
                            ("DELETE", "削除"),
                            ("PRINT", "印刷"),
                            ("EXPORT", "エクスポート"),
                        ],
                        max_length=10,
                        verbose_name="アクション",
                    ),
                ),
                ("summary", models.TextField(verbose_name="概要")),
                ("meta", models.JSONField(default=dict, verbose_name="メタデータ")),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IPアドレス"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="ユーザーエージェント"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rtms_app.patient",
                        verbose_name="患者",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "監査ログ",
                "verbose_name_plural": "監査ログ",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="rtms_app_au_created_9e218a_idx"
                    ),
                    models.Index(
                        fields=["patient"], name="rtms_app_au_patient_460283_idx"
                    ),
                    models.Index(
                        fields=["action"], name="rtms_app_au_action_c6c47e_idx"
                    ),
                ],
            },
        ),
    ]
