# Generated by Django 5.0.14 on 2025-12-17 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms_app", "0016_alter_assessment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentsession",
            name="coil_type",
            field=models.CharField(blank=True, default="H1", max_length=32),
        ),
        migrations.AddField(
            model_name="treatmentsession",
            name="frequency_hz",
            field=models.DecimalField(decimal_places=1, default=18.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="treatmentsession",
            name="intensity_percent",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="treatmentsession",
            name="intertrain_seconds",
            field=models.DecimalField(decimal_places=1, default=20.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="treatmentsession",
            name="mt_percent",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="treatmentsession",
            name="sessions_per_day",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="treatmentsession",
            name="target_site",
            field=models.CharField(
                blank=True, default="左背外側前頭前野", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="treatmentsession",
            name="train_seconds",
            field=models.DecimalField(decimal_places=1, default=2.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="treatmentsession",
            name="treatment_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="treatmentsession",
            name="intensity",
            field=models.IntegerField(blank=True, null=True, verbose_name="強度"),
        ),
        migrations.AlterField(
            model_name="treatmentsession",
            name="motor_threshold",
            field=models.IntegerField(blank=True, null=True, verbose_name="MT"),
        ),
        migrations.AlterField(
            model_name="treatmentsession",
            name="total_pulses",
            field=models.PositiveIntegerField(default=1980),
        ),
        migrations.CreateModel(
            name="SideEffectCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rows", models.JSONField(blank=True, default=list)),
                ("memo", models.TextField(blank=True, default="")),
                (
                    "physician_signature",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="side_effect_check",
                        to="rtms_app.treatmentsession",
                    ),
                ),
            ],
        ),
    ]
