# Generated by Django 5.0.14 on 2025-12-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms_app", "0017_treatmentsession_coil_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentsession",
            name="train_count",
            field=models.PositiveSmallIntegerField(
                default=55, verbose_name="トレイン数"
            ),
        ),
    ]
