# Generated by Django 5.0.14 on 2025-12-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms_app", "0018_treatmentsession_train_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="mappingsession",
            name="helmet_position_a_x",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="例: 3.00",
                max_digits=5,
                null=True,
                verbose_name="ヘルメット位置a X",
            ),
        ),
        migrations.AddField(
            model_name="mappingsession",
            name="helmet_position_a_y",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="例: 1.00",
                max_digits=5,
                null=True,
                verbose_name="ヘルメット位置a Y",
            ),
        ),
        migrations.AddField(
            model_name="mappingsession",
            name="helmet_position_b_x",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="例: 9.00",
                max_digits=5,
                null=True,
                verbose_name="ヘルメット位置b X",
            ),
        ),
        migrations.AddField(
            model_name="mappingsession",
            name="helmet_position_b_y",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="例: 1.00",
                max_digits=5,
                null=True,
                verbose_name="ヘルメット位置b Y",
            ),
        ),
        migrations.AddField(
            model_name="mappingsession",
            name="intensity_percent",
            field=models.IntegerField(
                blank=True, help_text="例: 60", null=True, verbose_name="強度%"
            ),
        ),
        migrations.AddField(
            model_name="mappingsession",
            name="stimulus_intensity_mt_percent",
            field=models.IntegerField(
                blank=True, help_text="例: 120", null=True, verbose_name="刺激強度MT%"
            ),
        ),
    ]
