# Generated by Django 5.0.14 on 2025-12-17 14:11

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def dedupe_duplicates(apps, schema_editor):
    # Remove duplicate Assessment / MappingSession / TreatmentSession rows
    Assessment = apps.get_model('rtms_app', 'Assessment')
    MappingSession = apps.get_model('rtms_app', 'MappingSession')
    TreatmentSession = apps.get_model('rtms_app', 'TreatmentSession')

    # Helper to dedupe: keep the newest by date/id, delete others
    def _dedupe(model, group_fields, order_by_fields):
        qs = model.objects.values(*group_fields).annotate(c=Count('id')).filter(c__gt=1)
        for g in qs:
            filter_kwargs = {k: g[k] for k in group_fields}
            rows = model.objects.filter(**filter_kwargs).order_by(*order_by_fields)
            keep = list(rows)[0]
            to_delete = [r.id for r in rows[1:]]
            if to_delete:
                model.objects.filter(id__in=to_delete).delete()

    # Assessments: group by patient, course_number, timing, type; keep latest date then highest id
    try:
        _dedupe(Assessment, ['patient_id', 'course_number', 'timing', 'type'], ['-date', '-id'])
    except Exception:
        pass

    # MappingSession: group by patient, course_number, date, stimulation_site; keep latest id
    try:
        _dedupe(MappingSession, ['patient_id', 'course_number', 'date', 'stimulation_site'], ['-id'])
    except Exception:
        pass

    # TreatmentSession: group by patient, course_number, session_date, slot; keep latest id
    try:
        _dedupe(TreatmentSession, ['patient_id', 'course_number', 'session_date', 'slot'], ['-id'])
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("rtms_app", "0019_mappingsession_helmet_position_a_x_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="course_number",
            field=models.IntegerField(
                db_index=True, default=1, verbose_name="クール数"
            ),
        ),
        # (Data cleanup will run after all new fields are present, before adding constraints)
        migrations.AddField(
            model_name="mappingsession",
            name="course_number",
            field=models.IntegerField(
                db_index=True, default=1, verbose_name="クール数"
            ),
        ),
        migrations.AddField(
            model_name="treatmentsession",
            name="course_number",
            field=models.IntegerField(
                db_index=True, default=1, verbose_name="クール数"
            ),
        ),
        migrations.AddField(
            model_name="treatmentsession",
            name="session_date",
            field=models.DateField(
                db_index=True, default=django.utils.timezone.now, verbose_name="実施日"
            ),
        ),
        migrations.AddField(
            model_name="treatmentsession",
            name="slot",
            field=models.CharField(
                blank=True, default="", max_length=8, verbose_name="スロット"
            ),
        ),
        migrations.RunPython(code=dedupe_duplicates, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.UniqueConstraint(
                fields=("patient", "course_number", "timing", "type"),
                name="unique_assessment_per_patient_course_timing_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="mappingsession",
            constraint=models.UniqueConstraint(
                fields=("patient", "course_number", "date", "stimulation_site"),
                name="unique_mapping_per_patient_course_date_site",
            ),
        ),
        migrations.AddConstraint(
            model_name="treatmentsession",
            constraint=models.UniqueConstraint(
                fields=("patient", "course_number", "session_date", "slot"),
                name="unique_treatment_per_patient_course_date_slot",
            ),
        ),
    ]
