# Generated by Django 5.0.14 on 2025-12-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms_app", "0022_assessment_hub_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="timing",
            field=models.CharField(
                choices=[
                    ("baseline", "治療前評価"),
                    ("week3", "3週目評価"),
                    ("week4", "4週目評価"),
                    ("week6", "6週目評価"),
                    ("other", "その他"),
                ],
                default="other",
                max_length=20,
                verbose_name="時期",
            ),
        ),
        migrations.AlterField(
            model_name="mappingsession",
            name="week_number",
            field=models.IntegerField(
                choices=[
                    (1, "第1週"),
                    (2, "第2週"),
                    (3, "第3週"),
                    (4, "第4週"),
                    (5, "第5週"),
                    (6, "第6週"),
                    (7, "第7週"),
                    (8, "第8週"),
                ],
                default=1,
                verbose_name="時期",
            ),
        ),
    ]
