# Generated by Django 5.0.14 on 2025-12-24 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms_app", "0024_protocol_sae_report_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdverseEventReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="['seizure', 'finger_muscle', 'syncope', 'mania', 'suicide_attempt', 'other'] など",
                        verbose_name="有害事象種別",
                    ),
                ),
                (
                    "adverse_event_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="有害事象名"
                    ),
                ),
                (
                    "onset_date",
                    models.DateField(blank=True, null=True, verbose_name="発現日"),
                ),
                (
                    "age",
                    models.IntegerField(blank=True, null=True, verbose_name="年齢"),
                ),
                (
                    "sex",
                    models.CharField(blank=True, max_length=10, verbose_name="性別"),
                ),
                (
                    "initials",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="イニシャル"
                    ),
                ),
                (
                    "diagnosis_category",
                    models.CharField(
                        choices=[
                            ("depressive_episode", "うつ病エピソード"),
                            ("recurrent_depressive_disorder", "反復性うつ病性障害"),
                            ("other", "その他"),
                        ],
                        default="depressive_episode",
                        max_length=40,
                        verbose_name="診断分類",
                    ),
                ),
                (
                    "diagnosis_other_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="診断その他"
                    ),
                ),
                (
                    "concomitant_meds_text",
                    models.TextField(blank=True, verbose_name="併用薬"),
                ),
                (
                    "substance_intake_text",
                    models.TextField(
                        blank=True, verbose_name="薬物・アルコール・カフェイン摂取"
                    ),
                ),
                (
                    "seizure_history_flag",
                    models.BooleanField(
                        default=False, verbose_name="てんかん・けいれん発作既往"
                    ),
                ),
                (
                    "seizure_history_date_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="けいれん発作既往時期"
                    ),
                ),
                (
                    "rmt_value",
                    models.IntegerField(
                        blank=True,
                        help_text="% 単位は不要",
                        null=True,
                        verbose_name="安静運動閾値",
                    ),
                ),
                (
                    "intensity_value",
                    models.IntegerField(
                        blank=True,
                        help_text="% 単位は不要",
                        null=True,
                        verbose_name="刺激強度",
                    ),
                ),
                (
                    "stimulation_site_category",
                    models.CharField(
                        choices=[("left_dlpfc", "左DLPFC"), ("other", "その他")],
                        default="left_dlpfc",
                        max_length=20,
                        verbose_name="刺激部位分類",
                    ),
                ),
                (
                    "stimulation_site_other_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="刺激部位その他"
                    ),
                ),
                (
                    "treatment_course_number",
                    models.IntegerField(
                        blank=True,
                        help_text="course 内での通算セッション番号",
                        null=True,
                        verbose_name="通算治療回数",
                    ),
                ),
                (
                    "outcome_flags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="['recovery', 'improvement'] など複数可",
                        verbose_name="転帰",
                    ),
                ),
                (
                    "outcome_sequelae_text",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="後遺症詳細"
                    ),
                ),
                (
                    "outcome_date",
                    models.DateField(blank=True, null=True, verbose_name="転帰日"),
                ),
                (
                    "special_notes",
                    models.TextField(blank=True, verbose_name="特記事項"),
                ),
                (
                    "physician_comment",
                    models.TextField(blank=True, verbose_name="医師コメント"),
                ),
                (
                    "prefilled_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="プリフィル元スナップショット",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adverse_event_report",
                        to="rtms_app.treatmentsession",
                        verbose_name="治療セッション",
                    ),
                ),
            ],
            options={
                "verbose_name": "有害事象報告書",
                "verbose_name_plural": "有害事象報告書",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session"], name="rtms_app_ad_session_17daf7_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="rtms_app_ad_created_560c17_idx"
                    ),
                ],
            },
        ),
    ]
