# Generated by Django 5.0.14 on 2026-01-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtms_app', '0027_treatmentsession_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='protocol_type',
        ),
        migrations.AddField(
            model_name='patient',
            name='estimated_onset_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='原疾患（うつ病）推定発症月'),
        ),
        migrations.AddField(
            model_name='patient',
            name='estimated_onset_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='原疾患（うつ病）推定発症年'),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_other_psychiatric_history',
            field=models.CharField(choices=[('yes', '有'), ('no', '無'), ('unknown', '不明')], default='no', max_length=8, verbose_name='診断名（今回 rTMS の適応以外の精神疾患の既往）'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_all_case_survey',
            field=models.BooleanField(default=False, verbose_name='全例調査対象'),
        ),
        migrations.AddField(
            model_name='patient',
            name='psychiatric_history',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='既往精神疾患'),
        ),
        migrations.AddField(
            model_name='patient',
            name='psychiatric_history_other_text',
            field=models.TextField(blank=True, default='', verbose_name='既往精神疾患（その他）'),
        ),
        migrations.AlterField(
            model_name='treatmentsession',
            name='status',
            field=models.CharField(choices=[('planned', '予定'), ('done', '実施'), ('skipped', 'スキップ')], db_index=True, default='planned', max_length=16, verbose_name='ステータス'),
        ),
    ]
