# Generated by Django 5.0.14 on 2026-01-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtms_app', '0028_remove_patient_protocol_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_weight_unknown',
            field=models.BooleanField(default=False, verbose_name='体重不明'),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='体重 (kg)'),
        ),
    ]
