# Generated by Django 5.0.14 on 2026-01-14 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtms_app', '0029_patient_is_weight_unknown_patient_weight_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='performed_date',
            field=models.DateField(blank=True, help_text='記録上の実施日。マイグレーションで既存の date をコピー予定', null=True, verbose_name='実施日(記録)'),
        ),
        migrations.CreateModel(
            name='TreatmentSkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('postpone', '順延'), ('finish', '終了'), ('cancel', '中止')], max_length=16, verbose_name='種別')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='対象実施日')),
                ('reason', models.TextField(blank=True, default='', verbose_name='理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skips', to='rtms_app.treatmentsession')),
            ],
            options={
                'verbose_name': '治療スキップ',
                'verbose_name_plural': '治療スキップ',
            },
        ),
    ]
