# Generated by Django 5.0.14 on 2026-01-25 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtms_app', '0032_treatmentskip_undo_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='患者ユーザー'),
        ),
        migrations.CreateModel(
            name='PatientSurveySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.IntegerField(db_index=True, default=1, verbose_name='クール数')),
                ('phase', models.CharField(choices=[('pre', '治療前'), ('post', '治療後')], db_index=True, max_length=16, verbose_name='フェーズ')),
                ('status', models.CharField(choices=[('in_progress', '実施中'), ('submitted', '提出済')], db_index=True, default='in_progress', max_length=16, verbose_name='ステータス')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='開始日時')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提出日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_survey_sessions_started', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_sessions', to='rtms_app.patient')),
            ],
            options={
                'verbose_name': '患者自己記入式セッション',
                'verbose_name_plural': '患者自己記入式セッション',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(choices=[('bdi2', '日本版 BDI-II'), ('sds', 'SDS (Zung Self-Rating Depression Scale)'), ('sassj', 'SASS-J (社会適応自己評価尺度)'), ('phq9', 'PHQ-9 日本語版'), ('stai_x1', '日本版 STAI 状態不安 (X-1)'), ('stai_x2', '日本版 STAI 特性不安 (X-2)'), ('dai10', '薬に対するアンケート (DAI-10)')], max_length=20, verbose_name='検査')),
                ('answers', models.JSONField(blank=True, default=dict, null=True, verbose_name='回答')),
                ('total_score', models.IntegerField(default=0, verbose_name='合計点')),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='補足')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='rtms_app.patientsurveysession')),
            ],
            options={
                'verbose_name': '患者自己記入式回答',
                'verbose_name_plural': '患者自己記入式回答',
            },
        ),
        migrations.AddIndex(
            model_name='patientsurveysession',
            index=models.Index(fields=['patient', 'status'], name='rtms_app_pa_patient_3510f9_idx'),
        ),
        migrations.AddIndex(
            model_name='patientsurveysession',
            index=models.Index(fields=['patient', 'phase'], name='rtms_app_pa_patient_2ba750_idx'),
        ),
        migrations.AddIndex(
            model_name='patientsurveyresponse',
            index=models.Index(fields=['session', 'instrument'], name='rtms_app_pa_session_2bc7d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientsurveyresponse',
            constraint=models.UniqueConstraint(fields=('session', 'instrument'), name='unique_response_per_session_instrument'),
        ),
    ]
