# Generated by Django 5.0.14 on 2026-01-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtms_app', '0035_alter_patient_user_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='card_id',
            field=models.CharField(db_index=True, max_length=5, unique=True, verbose_name='患者ID'),
        ),
    ]
