# Generated by Django 5.0.14 on 2026-08-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtms_app', '0037_alter_card_id_unique_5digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='first_visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='初診日'),
        ),
    ]
