# Generated by Django 5.0.14 on 2026-08-20 22:11
# Note: hand-trimmed to include only the new MappingSchedule model. The
# auto-generated version also included a RemoveField('patient.first_visit_date')
# and an AlterField('patient.has_other_psychiatric_history') coming from
# pre-existing, unrelated model/migration drift — intentionally left out of
# scope here.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtms_app', '0039_seed_assessment_scales'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.IntegerField(db_index=True, default=1, verbose_name='クール数')),
                ('week_number', models.IntegerField(choices=[(1, '第1週'), (2, '第2週'), (3, '第3週'), (4, '第4週'), (5, '第5週'), (6, '第6週'), (7, '第7週'), (8, '第8週')], verbose_name='週')),
                ('planned_date', models.DateField(verbose_name='予定日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_schedules', to='rtms_app.patient')),
            ],
            options={
                'verbose_name': 'MT測定予定',
                'verbose_name_plural': 'MT測定予定',
            },
        ),
        migrations.AddConstraint(
            model_name='mappingschedule',
            constraint=models.UniqueConstraint(fields=('patient', 'course_number', 'week_number'), name='unique_mapping_schedule_per_patient_course_week'),
        ),
    ]
