# Generated by Django 5.0.14 on 2026-08-20 22:36
# Note: hand-trimmed to include only the new AssessmentSchedule model. The
# auto-generated version also included a RemoveField('patient.first_visit_date')
# and an AlterField('patient.has_other_psychiatric_history') coming from
# pre-existing, unrelated model/migration drift — intentionally left out of
# scope here.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtms_app', '0040_mapping_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.IntegerField(db_index=True, default=1, verbose_name='クール数')),
                ('timing', models.CharField(choices=[('baseline', '治療前評価'), ('week3', '3週目評価'), ('week4', '4週目評価'), ('week6', '6週目評価'), ('other', 'その他')], max_length=20, verbose_name='時期')),
                ('planned_date', models.DateField(verbose_name='予定日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_schedules', to='rtms_app.patient')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='rtms_app.scaledefinition')),
            ],
            options={
                'verbose_name': '評価予定',
                'verbose_name_plural': '評価予定',
            },
        ),
        migrations.AddConstraint(
            model_name='assessmentschedule',
            constraint=models.UniqueConstraint(fields=('patient', 'course_number', 'scale', 'timing'), name='unique_assessment_schedule_per_patient_course_scale_timing'),
        ),
    ]

