# Generated by Django 5.0.14 on 2026-08-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtms_app', '0041_assessment_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='first_visit_date',
        ),
        migrations.AlterField(
            model_name='patient',
            name='has_other_psychiatric_history',
            field=models.CharField(choices=[('yes', '有'), ('no', '無'), ('unknown', '不明')], default='yes', max_length=8, verbose_name='診断名（今回 rTMS の適応以外の精神疾患の既往）'),
        ),
    ]
