# Generated by Django 5.0.14 on 2026-09-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms_app", "0043_patient_first_visit_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TreatmentCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_number",
                    models.PositiveIntegerField(verbose_name="クール数"),
                ),
                (
                    "course_status",
                    models.CharField(
                        choices=[
                            ("waiting_admission", "入院待ち"),
                            ("inpatient_waiting_treatment", "入院中（rTMS待ち）"),
                            ("treatment_in_progress", "rTMS中"),
                            ("treatment_finished_waiting_discharge", "rTMS終了（退院待ち）"),
                            ("discharged", "退院済"),
                            ("cancelled", "中止"),
                            ("withdrawn", "撤回"),
                            ("on_hold", "保留"),
                        ],
                        db_index=True,
                        default="waiting_admission",
                        max_length=48,
                        verbose_name="クール状態",
                    ),
                ),
                (
                    "course_end_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        choices=[
                            ("completed", "完了"),
                            ("cancelled", "キャンセル"),
                            ("discontinued", "中止"),
                            ("physician_decision", "医師判断"),
                            ("adverse_event", "有害事象"),
                            ("withdrawn", "撤回"),
                        ],
                        max_length=32,
                        verbose_name="クール終了理由",
                    ),
                ),
                (
                    "chief_complaint",
                    models.TextField(blank=True, default="", verbose_name="主訴"),
                ),
                (
                    "diagnosis",
                    models.CharField(default="うつ病", max_length=200, verbose_name="診断名"),
                ),
                (
                    "life_history",
                    models.TextField(blank=True, default="", verbose_name="生活歴"),
                ),
                (
                    "past_history",
                    models.TextField(blank=True, default="", verbose_name="既往歴"),
                ),
                (
                    "present_illness",
                    models.TextField(blank=True, default="", verbose_name="現病歴"),
                ),
                (
                    "medication_history",
                    models.TextField(blank=True, default="", verbose_name="薬剤治療歴"),
                ),
                (
                    "has_other_psychiatric_history",
                    models.CharField(
                        choices=[("yes", "有"), ("no", "無"), ("unknown", "不明")],
                        default="yes",
                        max_length=8,
                        verbose_name="その他の精神疾患既往",
                    ),
                ),
                (
                    "psychiatric_history",
                    models.JSONField(blank=True, default=list, null=True, verbose_name="既往精神疾患"),
                ),
                (
                    "psychiatric_history_other_text",
                    models.TextField(blank=True, default="", verbose_name="既往精神疾患（その他）"),
                ),
                (
                    "estimated_onset_year",
                    models.IntegerField(blank=True, null=True, verbose_name="原疾患推定発症年"),
                ),
                (
                    "estimated_onset_month",
                    models.IntegerField(blank=True, null=True, verbose_name="原疾患推定発症月"),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="体重 (kg)",
                    ),
                ),
                (
                    "is_weight_unknown",
                    models.BooleanField(default=False, verbose_name="体重不明"),
                ),
                (
                    "referral_source",
                    models.CharField(blank=True, default="", max_length=200, verbose_name="紹介元医療機関"),
                ),
                (
                    "referral_doctor",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="紹介医"),
                ),
                (
                    "first_visit_date",
                    models.DateField(blank=True, null=True, verbose_name="初診日"),
                ),
                (
                    "admission_date",
                    models.DateField(blank=True, null=True, verbose_name="入院予定日"),
                ),
                (
                    "admission_type",
                    models.CharField(
                        choices=[
                            ("voluntary", "任意入院"),
                            ("medical_protection", "医療保護入院"),
                            ("emergency", "緊急措置入院"),
                            ("measure", "措置入院"),
                        ],
                        default="voluntary",
                        max_length=20,
                        verbose_name="入院形態",
                    ),
                ),
                (
                    "is_admission_procedure_done",
                    models.BooleanField(default=False, verbose_name="入院手続き完了"),
                ),
                (
                    "first_treatment_date",
                    models.DateField(blank=True, null=True, verbose_name="初回治療日"),
                ),
                (
                    "mapping_date",
                    models.DateField(blank=True, null=True, verbose_name="初回位置決め日"),
                ),
                (
                    "mapping_notes",
                    models.TextField(blank=True, default="", verbose_name="位置決め記録メモ"),
                ),
                (
                    "is_all_case_survey",
                    models.BooleanField(default=False, verbose_name="全例調査対象"),
                ),
                (
                    "questionnaire_data",
                    models.JSONField(blank=True, default=dict, null=True, verbose_name="適正質問票"),
                ),
                (
                    "summary_text",
                    models.TextField(blank=True, default="", verbose_name="サマリー本文"),
                ),
                (
                    "discharge_prescription",
                    models.TextField(blank=True, default="", verbose_name="退院時処方"),
                ),
                (
                    "discharge_date",
                    models.DateField(blank=True, null=True, verbose_name="退院日"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="治療完了日時"),
                ),
                (
                    "discharged_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="退院確定日時"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "attending_physician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="担当医",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treatment_courses",
                        to="rtms_app.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "治療クール",
                "verbose_name_plural": "治療クール",
                "indexes": [
                    models.Index(fields=["patient", "course_status"], name="rtms_app_tr_patient_5ef2e4_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("patient", "course_number"),
                        name="unique_treatment_course_per_patient_number",
                    ),
                ],
            },
        ),
    ]
