# Generated by Django 5.0.14 on 2026-09-01 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtms_app', '0045_populate_treatment_courses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentsession',
            name='treatment_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treatment_sessions', to='rtms_app.treatmentcourse'),
        ),
        migrations.AddConstraint(
            model_name='treatmentsession',
            constraint=models.UniqueConstraint(fields=('treatment_course', 'session_date', 'slot'), name='unique_treatment_per_course_date_slot'),
        ),
    ]
