# Generated by Django 5.0.14 on 2026-09-01 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtms_app', '0047_populate_treatment_session_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='treatment_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='rtms_app.treatmentcourse'),
        ),
        migrations.AddField(
            model_name='assessmentrecord',
            name='treatment_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_records', to='rtms_app.treatmentcourse'),
        ),
        migrations.AddField(
            model_name='assessmentschedule',
            name='treatment_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_schedules', to='rtms_app.treatmentcourse'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('treatment_course', 'timing', 'type'), name='unique_assessment_per_treatment_course_timing_type'),
        ),
        migrations.AddConstraint(
            model_name='assessmentrecord',
            constraint=models.UniqueConstraint(fields=('treatment_course', 'timing', 'scale'), name='unique_assessment_record_per_treatment_course_timing_scale'),
        ),
        migrations.AddConstraint(
            model_name='assessmentschedule',
            constraint=models.UniqueConstraint(fields=('treatment_course', 'scale', 'timing'), name='unique_assessment_schedule_per_treatment_course_scale_timing'),
        ),
    ]
