# Generated by Django 5.0.14 on 2026-09-01 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtms_app', '0049_populate_assessment_treatment_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingschedule',
            name='treatment_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapping_schedules', to='rtms_app.treatmentcourse'),
        ),
        migrations.AddField(
            model_name='mappingsession',
            name='treatment_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapping_sessions', to='rtms_app.treatmentcourse'),
        ),
        migrations.AddConstraint(
            model_name='mappingschedule',
            constraint=models.UniqueConstraint(fields=('treatment_course', 'week_number'), name='unique_mapping_schedule_per_treatment_course_week'),
        ),
        migrations.AddConstraint(
            model_name='mappingsession',
            constraint=models.UniqueConstraint(fields=('treatment_course', 'date', 'stimulation_site'), name='unique_mapping_per_treatment_course_date_site'),
        ),
    ]
