# Generated by Django 5.0.14 on 2026-09-15 09:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtms_app', '0051_populate_mapping_treatment_courses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RtmSWaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', '希望受付'), ('waiting', '日程調整待ち'), ('provisional', '仮予定'), ('scheduled', '確定予定'), ('cancelled', 'キャンセル'), ('withdrawn', '撤回')], db_index=True, default='requested', max_length=16, verbose_name='状態')),
                ('priority', models.PositiveIntegerField(db_index=True, default=0, verbose_name='優先度')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='待機登録日時')),
                ('preferred_start_from', models.DateField(blank=True, null=True, verbose_name='希望開始日（早い方）')),
                ('preferred_start_to', models.DateField(blank=True, null=True, verbose_name='希望開始日（遅い方）')),
                ('estimated_inpatient_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='入院見込み日数')),
                ('preferred_treatment_start', models.DateField(blank=True, null=True, verbose_name='治療開始希望日')),
                ('comment', models.TextField(blank=True, default='', verbose_name='コメント')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='予定化日時')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'rTMS待機リスト',
                'verbose_name_plural': 'rTMS待機リスト',
            },
        ),
        migrations.CreateModel(
            name='InpatientPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('provisional', '仮予定'), ('scheduled', '確定予定'), ('admitted', '入院中'), ('discharged', '退院済'), ('cancelled', 'キャンセル')], db_index=True, default='draft', max_length=16, verbose_name='状態')),
                ('planned_admission_date', models.DateField(blank=True, null=True, verbose_name='入院予定日')),
                ('actual_admission_at', models.DateTimeField(blank=True, null=True, verbose_name='実入院日時')),
                ('estimated_discharge_date', models.DateField(blank=True, null=True, verbose_name='内部推定退院日')),
                ('planned_discharge_date', models.DateField(blank=True, null=True, verbose_name='臨床的退院予定日')),
                ('actual_discharge_at', models.DateTimeField(blank=True, null=True, verbose_name='実退院日時')),
                ('admission_type', models.CharField(choices=[('voluntary', '任意入院'), ('medical_protection', '医療保護入院'), ('emergency', '緊急措置入院'), ('measure', '措置入院')], default='voluntary', max_length=20, verbose_name='入院形態')),
                ('uncertainty', models.CharField(choices=[('confirmed', '確定'), ('provisional', '仮'), ('unknown', '不明')], default='confirmed', max_length=16, verbose_name='不確実性')),
                ('notes', models.TextField(blank=True, default='', verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inpatient_plans', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('treatment_course', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inpatient_plan', to='rtms_app.treatmentcourse', verbose_name='治療クール')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inpatient_plans', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '入院計画',
                'verbose_name_plural': '入院計画',
            },
        ),
        migrations.CreateModel(
            name='ResourceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start_date', models.DateField(verbose_name='予定開始日')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='予定終了日')),
                ('actual_start_at', models.DateTimeField(blank=True, null=True, verbose_name='実使用開始日時')),
                ('actual_end_at', models.DateTimeField(blank=True, null=True, verbose_name='実使用終了日時')),
                ('status', models.CharField(choices=[('planned', '予定'), ('active', '使用中'), ('completed', '終了'), ('cancelled', 'キャンセル')], db_index=True, default='planned', max_length=16, verbose_name='状態')),
                ('certainty', models.CharField(choices=[('confirmed', '確定'), ('provisional', '仮'), ('estimated', '推定'), ('unknown', '不明')], default='confirmed', max_length=16, verbose_name='確度')),
                ('reason', models.TextField(blank=True, default='', verbose_name='理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_resource_assignments', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('treatment_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resource_assignments', to='rtms_app.treatmentcourse', verbose_name='治療クール')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_resource_assignments', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '資源割当',
                'verbose_name_plural': '資源割当',
            },
        ),
        migrations.CreateModel(
            name='ResourcePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='資源コード')),
                ('name', models.CharField(max_length=128, verbose_name='資源名')),
                ('resource_type', models.CharField(choices=[('rTMS_private', 'rTMS個室'), ('general_ward', '一般病棟'), ('other_inpatient', 'その他の入院資源')], max_length=32, verbose_name='資源種別')),
                ('physical_capacity', models.PositiveIntegerField(verbose_name='物理容量')),
                ('operational_target', models.PositiveIntegerField(verbose_name='通常運用枠')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='有効')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='有効開始日')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='有効終了日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '資源プール',
                'verbose_name_plural': '資源プール',
                'indexes': [models.Index(fields=['resource_type', 'is_active'], name='rtms_app_re_resourc_621952_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='resourcepool',
            constraint=models.CheckConstraint(check=models.Q(('operational_target__lte', models.F('physical_capacity'))), name='resource_pool_operational_target_lte_capacity'),
        ),
        migrations.AddConstraint(
            model_name='resourcepool',
            constraint=models.CheckConstraint(check=models.Q(('valid_to__isnull', True), ('valid_from__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='resource_pool_valid_to_gte_valid_from'),
        ),
        migrations.AddField(
            model_name='resourceassignment',
            name='resource_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='rtms_app.resourcepool', verbose_name='資源プール'),
        ),
        migrations.AddField(
            model_name='rtmswaitlistentry',
            name='inpatient_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='rtms_app.inpatientplan', verbose_name='入院計画'),
        ),
        migrations.AddField(
            model_name='rtmswaitlistentry',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_rtms_waitlist_entries', to=settings.AUTH_USER_MODEL, verbose_name='登録者'),
        ),
        migrations.AddField(
            model_name='rtmswaitlistentry',
            name='treatment_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rtms_waitlist_entries', to='rtms_app.treatmentcourse', verbose_name='治療クール'),
        ),
        migrations.AddIndex(
            model_name='inpatientplan',
            index=models.Index(fields=['status', 'planned_admission_date'], name='rtms_app_in_status_df1cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='inpatientplan',
            index=models.Index(fields=['planned_discharge_date'], name='rtms_app_in_planned_39fbe2_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceassignment',
            index=models.Index(fields=['resource_pool', 'planned_start_date'], name='rtms_app_re_resourc_5bd169_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceassignment',
            index=models.Index(fields=['treatment_course', 'status'], name='rtms_app_re_treatme_3e44bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='resourceassignment',
            constraint=models.CheckConstraint(check=models.Q(('planned_end_date__isnull', True), ('planned_end_date__gte', models.F('planned_start_date')), _connector='OR'), name='resource_assignment_planned_end_gte_start'),
        ),
        migrations.AddConstraint(
            model_name='resourceassignment',
            constraint=models.CheckConstraint(check=models.Q(('actual_start_at__isnull', True), ('actual_end_at__isnull', True), ('actual_end_at__gte', models.F('actual_start_at')), _connector='OR'), name='resource_assignment_actual_end_gte_start'),
        ),
        migrations.AddIndex(
            model_name='rtmswaitlistentry',
            index=models.Index(fields=['status', 'priority', 'registered_at'], name='rtms_app_rt_status_5df452_idx'),
        ),
        migrations.AddIndex(
            model_name='rtmswaitlistentry',
            index=models.Index(fields=['treatment_course', 'status'], name='rtms_app_rt_treatme_b63c54_idx'),
        ),
        migrations.AddConstraint(
            model_name='rtmswaitlistentry',
            constraint=models.CheckConstraint(check=models.Q(('preferred_start_to__isnull', True), ('preferred_start_from__isnull', True), ('preferred_start_to__gte', models.F('preferred_start_from')), _connector='OR'), name='waitlist_preferred_start_to_gte_from'),
        ),
    ]
