# Generated by Django 5.0.14 on 2026-09-16 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtms_app', '0052_rtmswaitlistentry_inpatientplan_resourceassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RtmSAdmissionCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(verbose_name='rTMS新規入院受入枠')),
                ('valid_from', models.DateField(verbose_name='有効開始日')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='有効終了日')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='有効')),
                ('notes', models.TextField(blank=True, default='', verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rtms_admission_capacities', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_rtms_admission_capacities', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'rTMS新規入院受入枠',
                'verbose_name_plural': 'rTMS新規入院受入枠',
                'indexes': [models.Index(fields=['valid_from', 'valid_to', 'is_active'], name='rtms_app_rt_valid_f_7c3131_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='rtmsadmissioncapacity',
            constraint=models.CheckConstraint(check=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='rtms_admission_capacity_valid_to_gte_from'),
        ),
    ]
