# Generated by Django 5.0.14 on 2026-09-16 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtms_app', '0054_treatmentcourse_private_room_planned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rtmswaitlistentry',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('requested', 'waiting', 'provisional', 'scheduled'))), fields=('treatment_course',), name='unique_active_waitlist_per_treatment_course'),
        ),
    ]
